- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/platforms/aarch64_macos.rs
- src/platforms/mod.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/platforms/x86_64_macos.rs
- src/platforms/x86_64_windows_gnu.rs
- src/utils.rs
- src/zkevm_llvm/arguments.rs
- src/zkevm_llvm/main.rs
Add a new option:
> --extra-args <extra-args>...    Extra arguments to pass to CMake. A leading backslash will be unescaped
Tested on Ubuntu 22.04.1 LTS Jammy Jellyfish on x86_64, our [GitHub Action](https://github.com/matter-labs/compiler-llvm/actions/runs/5159734660/jobs/9295708943), and MacOS 12.6.2 21G320 on M1 Max
Let me know if I should create some VMs to test other platforms.
> Pass arbitrary CMake options to llvm-builder

- src/lib.rs
- src/platforms/aarch64_linux_gnu.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/aarch64_macos.rs
- src/platforms/mod.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/platforms/x86_64_macos.rs
- src/platforms/x86_64_windows_gnu.rs
- src/zkevm_llvm/arguments.rs
- src/zkevm_llvm/main.rs
Add support for [compiler cache](https://ccache.dev/) during the build process for all targets.
It helps to significantly increase compilation speed by recompiling only changed source files. It can be used locally or in CI to get significant speed-up for our LLVM backend builds.
> feat: add support for compiler cache (ccache)

- .github/workflows/build-and-test.yaml
- Cargo.lock
- Cargo.toml
- src/build_type.rs
- src/platforms/aarch64_linux_gnu.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/aarch64_macos.rs
- src/platforms/shared.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/platforms/x86_64_macos.rs
- src/platforms/x86_64_windows_gnu.rs
- tests/build.rs
Disables assertions for cross-compilation targets to unblock Linux Musl builds
See [CPR-1592](https://linear.app/matterlabs/issue/CPR-1592/linux-musl-llvm-targets-cannot-be-built-with-assertions) for more info
> fix: disable assertions

- .github/workflows/build-and-test.yaml
- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/zkevm_llvm/arguments.rs
- src/zkevm_llvm/main.rs
- tests/clone.rs
Fixes [CPR-1589](https://linear.app/matterlabs/issue/CPR-1589/optimize-clone-operation-of-zkevm-llvm-builder)
Adds `--shallow` option to make fast clones.
There are many places in CI where we don't need to clone with the whole history and spend >4m or even more for that. Sometimes, we want just the fastest clone possible. More info about different clone types and analysis are available in [CPR-1589](https://linear.app/matterlabs/issue/CPR-1589/optimize-clone-operation-of-zkevm-llvm-builder).
> feat: add fast shallow clone support

- .github/workflows/build-and-test.yaml
- .github/workflows/cargo-license.yaml
- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/platforms/aarch64_linux_musl.rs
- src/platforms/x86_64_linux_musl.rs
- tests/common/mod.rs
Updates to LLVM 17.
Versions 1.4.1 of compilers and 1.4.2 of LLVM have been updated.
> chore: update to LLVM 17

- .github/workflows/build-and-test.yaml
- Cargo.lock
- Cargo.toml
- src/platforms/aarch64_macos.rs
- src/platforms/shared.rs
- src/platforms/x86_64_macos.rs
- src/utils.rs
- tests/common/mod.rs
Disable duplicate library warnings on XCode >= 15.
To have clean output logs.
> chore: fix library duplication warnings for macos builds

- .github/actions/build_and_test/action.yml
- .github/actions/prepare-msys/action.yml
- .github/workflows/build-and-test.yaml
- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/llvm_path.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/mod.rs
- src/platforms/x86_64_linux_musl.rs
- src/utils.rs
- src/zkevm_llvm/arguments.rs
- src/zkevm_llvm/main.rs
- tests/build.rs
* To fix sporadic Musl download failures across all workflows
* To ease CI support in the future
* To simplify installation instructions for LLVM builder and allow Musl and Gnu builds with the same standard LLVM builder binaries
> feat: separate musl from targets, native downloader and ci update 

- Cargo.toml
- src/platforms/aarch64_linux_musl.rs
- src/platforms/shared.rs
- src/platforms/x86_64_linux_musl.rs
Related to proper fix of [CPR-1581](https://linear.app/matterlabs/issue/CPR-1581/undocumented-additional-zksolczkvyper-cross-compile-build-options).
> feat: enable crt builtins for aarch64

- Cargo.lock
- rust-toolchain.toml
- src/platforms/aarch64_linux_musl.rs
- src/platforms/shared.rs
- src/platforms/x86_64_linux_musl.rs
- src/utils.rs
Checks all conditions for Musl download retries.
The tool was panicking if any attempt to download Musl failed even if a retry succeeds. This fixes this behavior by checking all attempts and failing only if all of them failed.
> fix: check all retries in musl download condition

- .github/actions/build_and_test/action.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/build_type.rs
- src/lib.rs
- src/llvm_path.rs
- src/lock.rs
- src/platforms/aarch64_linux_gnu.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/aarch64_macos.rs
- src/platforms/mod.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/platforms/x86_64_macos.rs
- src/platforms/x86_64_windows_gnu.rs
- src/zksync_llvm/arguments.rs
- src/zksync_llvm/main.rs
- tests/build.rs
- tests/checkout.rs
- tests/clean.rs
- tests/clone.rs
- tests/common/mod.rs
- tests/invalid_invocation.rs
- tests/version.rs
Fixes [CPR-1674](https://linear.app/matterlabs/issue/CPR-1674/make-compiler-builder-unit-tests-independent-from-the-commit)
To correspond to our new naming conventions and stabilize tests execution.
> feat!: rename zkevm-llvm to zksync-llvm 

- src/platforms/shared.rs
Add `LLVM_ENABLE_WERROR` and `CMAKE_EXPORT_COMPILE_COMMANDS` to default cmake flags.
These are additional parameters we always use for our builds, make them default instead of always specifying them explicitly across the ecosystem.
> feat: add LLVM_ENABLE_WERROR and CMAKE_EXPORT_COMPILE_COMMANDS to default flags

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/platforms/aarch64_linux_gnu.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/aarch64_macos.rs
- src/platforms/mod.rs
- src/platforms/shared.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/platforms/x86_64_macos.rs
- src/platforms/x86_64_windows_gnu.rs
- src/target_env.rs
- src/target_triple.rs
- src/zksync_llvm/arguments.rs
Introduce a new `TargetTriple` enum for triple values, as the `Platform` is different from the triple, and `EraVM`/`EVM` targets cannot be used as a triple value, they should be lowercase.
Decided to implement as a separate enum, because triple and platform values can differ, and converting `Platform` to the lowercase can break in the future.
To fix `llc` behavior when triple is not lowercase as LLVM cannot handle this.
> fix: set LLVM_DEFAULT_TARGET_TRIPLE to always be lowercase

- Cargo.lock
- Cargo.toml
- src/platforms/aarch64_linux_musl.rs
- src/platforms/x86_64_linux_musl.rs
Build compiler-rt profile library for stage1 musl builds.
To fix `--enable-coverage` option under Musl targets.
> fix: build crt profile for coverage support on musl

- Cargo.lock
- Cargo.toml
- src/build_type.rs
- src/zksync_llvm/arguments.rs
- src/zksync_llvm/main.rs
- tests/build.rs
Support two additional build types `RelWithDebInfo` and `MinSizeRel`.
Sometimes, these build types can be required in debugging purposes.
> feat: support all LLVM build types

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/platforms/aarch64_linux_gnu.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/shared.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/zksync_llvm/arguments.rs
- src/zksync_llvm/main.rs
Add the capability to run LLVM regression tests under `valgrind` if necessary.
To allow developers to find memory-related issues with LLVM.
> feat: add capability to run LLVM regression tests under valgrind

- .github/workflows/build-and-test.yaml
- Cargo.lock
- Cargo.toml
- src/lib.rs
Remove `gnu` condition from the Windows build branch.
In some cases where `gnu` is undefined:
["For historical reasons, this value is only defined as not the empty-string when actually needed for disambiguation. Thus, for example, on many GNU platforms, this value will be empty."
](https://doc.rust-lang.org/reference/conditional-compilation.html#target_env:~:text=or%20libc%20used.-,For%20historical%20reasons%2C%20this%20value%20is%20only%20defined%20as%20not%20the%20empty%2Dstring%20when%20actually%20needed%20for%20disambiguation.%20Thus%2C%20for%20example%2C%20on%20many%20GNU%20platforms%2C%20this%20value%20will%20be%20empty.,-This%20value%20is)
This is required to properly fix MSYS2 regression tests on Windows.
> chore: remove gnu condition from Windows

- Cargo.lock
- Cargo.toml
- src/platforms/shared.rs
Use python from PATH, and not from registry.
Unfortunately, just adding the right python in PATH is not enough, and to not implement workarounds and also fix potential Windows Python discovery issues for our users, we need to remove CMake python search from registry on Windows:
* https://github.com/actions/setup-python/issues/186
* https://cmake.org/cmake/help/v3.12/module/FindPython.html
> fix: use python from PATH and not from registry

- Cargo.toml
- src/platforms/x86_64_windows_gnu.rs
Remove unnecessary `libstdc++` copying on Windows.
This copying causes issues with duplicated symbols like: `multiple definition of std::__cxx11::basic_string`.
Example of the problem: https://github.com/matter-labs/era-compiler-llvm/actions/runs/10887318886/job/30209296538
> fix: remove windows custom libstdc++

- Cargo.toml
- src/platforms/x86_64_windows_gnu.rs
This reverts commit fb986a43c44e2ae056484504b83cbae3a3aa71fa.
* We were copying GNU libstdc++ static lib from msys64/mingw to the LLVM folder with static libs.
* llvm-sys takes this libstdc++ just because it's in this directory and links with it
* additionally, llvm-sys build.rs adds dynamic libstdc++ to be linked on Windows
* +crt-static Rust flag is not recognizable by build.rs on Windows
Although it can cause some issues with tester (due to dynamic and static linkage mix), there is no beautiful and other way for now to link properly. It's better to revert now to unblock testing and releases in zksolc/zkvyper.
Related issue: https://github.com/rust-lang/rust/issues/24345
> Revert "fix: remove windows custom libstdc++ (#42)"

- .github/pull_request_template.md
- Cargo.lock
- Cargo.toml
- deny.toml
- src/build_type.rs
- src/ccache_variant.rs
- src/lib.rs
- src/platforms/aarch64_linux_gnu.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/aarch64_macos.rs
- src/platforms/shared.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/platforms/x86_64_macos.rs
- src/platforms/x86_64_windows_gnu.rs
- src/target_env.rs
- src/zksync_llvm/arguments.rs
- src/zksync_llvm/main.rs
Fixes https://github.com/matter-labs/era-compiler-solidity/issues/206
> fix: replace structopt with clap

- src/platforms/shared.rs
Use `https://github.com/matter-labs/era-compiler-llvm/issues/` bug report URL instead of default LLVM one.
To suggest users reporting LLVM bugs to us instead of upstream.
> chore: use the Matter Labs bug report URL for LLVM

- src/build_type.rs
- src/ccache_variant.rs
- src/lib.rs
- src/llvm_project.rs
- src/lock.rs
- src/platforms/aarch64_linux_gnu.rs
- src/platforms/aarch64_linux_musl.rs
- src/platforms/aarch64_macos.rs
- src/platforms/mod.rs
- src/platforms/shared.rs
- src/platforms/x86_64_linux_gnu.rs
- src/platforms/x86_64_linux_musl.rs
- src/platforms/x86_64_macos.rs
- src/platforms/x86_64_windows_gnu.rs
- src/sanitizer.rs
- src/target_env.rs
- src/target_triple.rs
- src/utils.rs
- src/zksync_llvm/arguments.rs
- src/zksync_llvm/main.rs
Fixes `--extra-args` with multiple args.
Apparently it was broken by the last `cargo update`.
> fix: --extra-args with multiple args
